version: '3.2'
services:

  ########################
  # MyPain
  ########################
  my-pain:
    image: contentgroup/mypain:latest
    ports:
      - "80"
    # Tells the reverse proxy to expose the container of my-pain.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mypain.rule=Host(`my-pain.localhost`)"
      - "traefik.http.routers.mypain.entrypoints=web"

  ########################
  # PainManager
  ########################
  pain-manager:
    image: contentgroup/painmanager:develop
    ports:
      - "80"
    # Tells the reverse proxy to expose the container of pain-manager.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.painmanager.rule=Host(`pain-manager.localhost`)"
      - "traefik.http.routers.painmanager.entrypoints=web"

  ########################
  # CQF-Ruler
  ########################
  cqf-ruler:
    image: contentgroup/cqf-ruler:latest
    environment:
      - "JAVA_OPTIONS=-Dhapi.properties.R4=/var/lib/jetty/target/config/r4.properties -Dhapi.properties.DSTU3=/var/lib/jetty/target/config/dstu3.properties"
    volumes:
    # Shares configuration with the cqf-ruler
      - './config/cqf-ruler/config:/var/lib/jetty/target/config:ro'
    # Shares sample data with the cqf-ruler
      - './config/cqf-ruler/h2:/var/lib/jetty/target/database/h2:rw'
    ports:
      - "8080"
    # Tells the reverse proxy to expose the container of cqf-ruler.localhost
    links:
      - "traefik:cqf-ruler.localhost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cqf-ruler.rule=Host(`cqf-ruler.localhost`)"
      - "traefik.http.routers.cqf-ruler.entrypoints=web"

  ########################
  # Smart Launcher
  ########################
  smart-launcher:
    image: contentgroup/smart-launcher:latest
    environment: 
      - "FHIR_SERVER_R4=http://cqf-ruler.localhost/fhir"
      - "FHIR_SERVER_R3=http://cqf-ruler.localhost/fhir"
      - "CDS_SANDBOX_URL=http://smart-launcher.localhost"
      - "BASE_URL=http://smart-launcher.localhost"
    ports:
      - "80"
    # Tells the reverse proxy to expose the container of smart-launcher.localhost
    links:
      - "traefik:cqf-ruler.localhost"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smart-launcher.rule=Host(`smart-launcher.localhost`)"
      - "traefik.http.routers.smart-launcher.entrypoints=web"

  ########################
  # Traefik
  ########################
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  