version: '3.2'
services:

  ########################
  # MyPain
  ########################
  my-pain:
    image: contentgroup/mypain:develop

  ########################
  # PainManager
  ########################
  pain-manager:
    image: contentgroup/painmanager:develop

  ########################
  # CQF-Ruler
  ########################
  cqf-ruler:
    image: contentgroup/cqf-ruler:develop
    environment:
      - "JAVA_OPTIONS=-Dhapi.properties.R4=/var/lib/jetty/target/config/r4.properties -Dhapi.properties.DSTU3=/var/lib/jetty/target/config/dstu3.properties"
    volumes:
    # Shares configuration with the cqf-ruler
      - '../services/cqf-ruler/config:/var/lib/jetty/target/config:ro'
    # Shares sample data with the cqf-ruler
      - '../services/cqf-ruler/h2:/var/lib/jetty/target/database/h2:rw'
    links:
      - "traefik:cqf-ruler.localhost"

  ########################
  # Smart Launcher
  ########################
  smart-launcher:
    image: contentgroup/smart-launcher:develop
    environment: 
      - "FHIR_SERVER_R4=http://cqf-ruler.localhost/cqf-ruler-r4/fhir"
      - "FHIR_SERVER_R3=http://cqf-ruler.localhost/cqf-ruler-dstu3/fhir"
      - "CDS_SANDBOX_URL=http://smart-launcher.localhost"
      - "BASE_URL=http://smart-launcher.localhost"
    links:
      - "traefik:cqf-ruler.localhost"

  ########################
  # Traefik
  ########################
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "../services/traefik/traefik.yaml:/traefik.yaml"
      - "../services/traefik/config:/config"

  